server:
  port: 9080
spring:
  rabbitmq:
    host: localhost
    username: sy
    password: 123
    port: 5672
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/rabbitmq
    username: root
    password: 123
